### PR TITLE
US2 Course function

### PR DESCRIPTION
**Pull request by HasanainAlameen**
Updated the CourseService Class and Course Class

### CODE REVIEW

**Review by mustafacihat — CHANGES_REQUESTED** [review]
You need to fix BaseEntity Class and in the Database class we have some unnecessary code.

**Comment by Rikhsiboev** [comment]
sound goods

**Comment by Rikhsiboev** [comment]
good to

**Review by mustafacihat — APPROVED** [review]
Good

**Comment by Rikhsiboev** [comment]
good
and prove

**Comment by Rikhsiboev** [comment]
good

**Review by Rikhsiboev — APPROVED** [review]
good

**Pull request merged**
