### PR TITLE
Denis-US01

### PR DESCRIPTION
**Pull request by denispupkov**
All Student entities added. All Student service methods are implemented. (not tested because database is not accesible)

### CODE REVIEW

**Comment by Nora85** [comment]
Great job, Denis!

**Review by mustafacihat — APPROVED** [review]
Thanks for your great effort Denis. Seems perfect. In my opinion instead of writing the filter operation again instead inside update method, you can call deleteById method.

**Comment by denispupkov** [comment]
> Thanks for your great effort Denis. Seems perfect. In my opinion instead of writing the filter operation again instead inside update method, you can call deleteById method.

Totally forgot about code reusability. Good point! Thank you Cihat!

**Review by Nora85 — APPROVED** [review]
Thank you so much for great job!!!

**Pull request merged**
