### PR TITLE
Start Project  

### PR DESCRIPTION
**Pull request by Rikhsiboev**
Hello guys i want to ask some quasion From what  we will star? i just want to use this pull request to understand flow below you can add you commit so we can start discuss all things here and see how flow communication works

### CODE REVIEW

**Review by denispupkov — APPROVED** [review]
Good start Bobur!

**Review by AlmiMeco — APPROVED** [review]
Good clean-up Bobur,

**Comment by Rikhsiboev** [comment]
so let's talk about all things, from User case 1 what king idia do you have? or Project logic ?

**Review by karamanesranur — APPROVED** [review]
good work

**Review by sulkemref — APPROVED** [review]
Agree

**Review by mustafacihat — APPROVED** [review]
Bobur I appreciate your interest in our study. I have created one pull request for all my friends. I know that this study is not entirely realistic and well-designed. This is just a warm-up for an agile environment and collaboration. So please check both my pull request and analyze what I have pushed to minimize your hesitation for the implementation of the project. DEAR FRIENDS DO NOT MERGE THIS PULL REQUEST and @Rikhsiboev please close this pull request.!!!!!!!!!

**Comment by Nora85** [comment]
Great job,Bobur !!

**Pull request merged**
